class AddAppropriateColumnsToStatTables < ActiveRecord::Migration
  def change
    add_column :season_batting_stats, :player_id, :integer
    add_column :season_batting_stats, :season_id, :integer
    add_column :season_batting_stats, :team_id, :integer
    add_column :season_batting_stats, :atbats, :integer
    add_column :season_batting_stats, :runs, :integer
    add_column :season_batting_stats, :hits, :integer
    add_column :season_batting_stats, :doubles, :integer
    add_column :season_batting_stats, :triples, :integer
    add_column :season_batting_stats, :home_runs, :integer
    add_column :season_batting_stats, :rbi, :integer
    add_column :season_batting_stats, :walks, :integer
    add_column :season_batting_stats, :intentional_walks, :integer
    add_column :season_batting_stats, :strikeouts, :integer
    add_column :season_batting_stats, :stolen_bases, :integer
    add_column :season_batting_stats, :caught_stealing, :integer
    add_column :season_batting_stats, :games, :integer

    add_column :season_fielding_stats, :player_id, :integer
    add_column :season_fielding_stats, :season_id, :integer
    add_column :season_fielding_stats, :team_id, :integer
    add_column :season_fielding_stats, :errors_committed, :integer
    add_column :season_fielding_stats, :assists, :integer
    add_column :season_fielding_stats, :putouts, :integer
    add_column :season_fielding_stats, :chances, :integer
    add_column :season_fielding_stats, :games, :integer

    add_column :season_pitching_stats, :player_id, :integer
    add_column :season_pitching_stats, :season_id, :integer
    add_column :season_pitching_stats, :team_id, :integer
    add_column :season_pitching_stats, :outs_recorded, :integer
    add_column :season_pitching_stats, :hits_allowed, :integer
    add_column :season_pitching_stats, :runs_allowed, :integer
    add_column :season_pitching_stats, :earned_runs_allowed, :integer
    add_column :season_pitching_stats, :walks_allowed, :integer
    add_column :season_pitching_stats, :strikeouts_recorded, :integer
    add_column :season_pitching_stats, :home_runs_allowed, :integer
    add_column :season_pitching_stats, :total_pitches, :integer
    add_column :season_pitching_stats, :strikes_thrown, :integer
    add_column :season_pitching_stats, :balls_thrown, :integer
    add_column :season_pitching_stats, :intentional_walks_allowed, :integer
    add_column :season_pitching_stats, :wins, :integer
    add_column :season_pitching_stats, :losses, :integer
    add_column :season_pitching_stats, :saves, :integer
    add_column :season_pitching_stats, :blown_saves, :integer
    add_column :season_pitching_stats, :holds, :integer
    add_column :season_pitching_stats, :games, :integer
    add_column :season_pitching_stats, :zone_1_pitches, :integer
    add_column :season_pitching_stats, :zone_2_pitches, :integer
    add_column :season_pitching_stats, :zone_3_pitches, :integer
    add_column :season_pitching_stats, :zone_4_pitches, :integer
    add_column :season_pitching_stats, :zone_5_pitches, :integer
    add_column :season_pitching_stats, :zone_6_pitches, :integer
    add_column :season_pitching_stats, :zone_7_pitches, :integer
    add_column :season_pitching_stats, :zone_8_pitches, :integer
    add_column :season_pitching_stats, :zone_9_pitches, :integer
    add_column :season_pitching_stats, :zone_10_pitches, :integer
    add_column :season_pitching_stats, :zone_11_pitches, :integer
    add_column :season_pitching_stats, :zone_12_pitches, :integer
    add_column :season_pitching_stats, :zone_13_pitches, :integer
    add_column :season_pitching_stats, :zone_14_pitches, :integer
    add_column :season_pitching_stats, :zone_15_pitches, :integer
    add_column :season_pitching_stats, :zone_16_pitches, :integer
    add_column :season_pitching_stats, :zone_17_pitches, :integer
    add_column :season_pitching_stats, :zone_18_pitches, :integer
    add_column :season_pitching_stats, :zone_19_pitches, :integer
    add_column :season_pitching_stats, :zone_20_pitches, :integer
    add_column :season_pitching_stats, :zone_21_pitches, :integer
    add_column :season_pitching_stats, :zone_22_pitches, :integer
    add_column :season_pitching_stats, :zone_23_pitches, :integer
    add_column :season_pitching_stats, :zone_24_pitches, :integer
    add_column :season_pitching_stats, :zone_25_pitches, :integer
    add_column :season_pitching_stats, :zone_26_pitches, :integer
    add_column :season_pitching_stats, :zone_27_pitches, :integer
    add_column :season_pitching_stats, :zone_28_pitches, :integer
    add_column :season_pitching_stats, :zone_29_pitches, :integer
    add_column :season_pitching_stats, :zone_30_pitches, :integer
    add_column :season_pitching_stats, :zone_31_pitches, :integer
    add_column :season_pitching_stats, :zone_32_pitches, :integer
    add_column :season_pitching_stats, :zone_33_pitches, :integer
    add_column :season_pitching_stats, :zone_34_pitches, :integer
    add_column :season_pitching_stats, :zone_35_pitches, :integer
    add_column :season_pitching_stats, :zone_36_pitches, :integer
    add_column :season_pitching_stats, :zone_37_pitches, :integer
    add_column :season_pitching_stats, :zone_38_pitches, :integer
    add_column :season_pitching_stats, :zone_39_pitches, :integer
    add_column :season_pitching_stats, :zone_40_pitches, :integer
    add_column :season_pitching_stats, :zone_41_pitches, :integer
    add_column :season_pitching_stats, :zone_42_pitches, :integer
    add_column :season_pitching_stats, :zone_43_pitches, :integer
    add_column :season_pitching_stats, :zone_44_pitches, :integer
    add_column :season_pitching_stats, :zone_45_pitches, :integer
    add_column :season_pitching_stats, :zone_46_pitches, :integer
    add_column :season_pitching_stats, :zone_47_pitches, :integer
    add_column :season_pitching_stats, :zone_48_pitches, :integer
    add_column :season_pitching_stats, :zone_49_pitches, :integer
    add_column :season_pitching_stats, :zone_50_pitches, :integer
    add_column :season_pitching_stats, :zone_51_pitches, :integer
    add_column :season_pitching_stats, :zone_52_pitches, :integer
    add_column :season_pitching_stats, :zone_53_pitches, :integer
    add_column :season_pitching_stats, :zone_54_pitches, :integer
    add_column :season_pitching_stats, :zone_55_pitches, :integer
    add_column :season_pitching_stats, :zone_56_pitches, :integer
    add_column :season_pitching_stats, :zone_57_pitches, :integer
    add_column :season_pitching_stats, :zone_58_pitches, :integer
    add_column :season_pitching_stats, :zone_59_pitches, :integer
    add_column :season_pitching_stats, :zone_60_pitches, :integer
    add_column :season_pitching_stats, :zone_61_pitches, :integer
    add_column :season_pitching_stats, :zone_62_pitches, :integer
    add_column :season_pitching_stats, :zone_63_pitches, :integer
    add_column :season_pitching_stats, :zone_64_pitches, :integer
    add_column :season_pitching_stats, :zone_65_pitches, :integer
    add_column :season_pitching_stats, :zone_66_pitches, :integer
    add_column :season_pitching_stats, :zone_67_pitches, :integer
    add_column :season_pitching_stats, :zone_68_pitches, :integer
    add_column :season_pitching_stats, :zone_69_pitches, :integer
    add_column :season_pitching_stats, :zone_70_pitches, :integer
    add_column :season_pitching_stats, :zone_71_pitches, :integer
    add_column :season_pitching_stats, :zone_72_pitches, :integer
  end
end
