class RemoveUnnecessaryColumnsFromPlayers < ActiveRecord::Migration
  def change
    remove_column :players, :age
    remove_column :players, :position
    remove_column :players, :salary
    remove_column :players, :power
    remove_column :players, :contact
    remove_column :players, :speed
    remove_column :players, :patience
    remove_column :players, :plate_vision
    remove_column :players, :pull_amount
    remove_column :players, :uppercut_amount
    remove_column :players, :batting_average
    remove_column :players, :movement
    remove_column :players, :control
    remove_column :players, :location
    remove_column :players, :agility
    remove_column :players, :reactionTime
    remove_column :players, :armStrength
    remove_column :players, :fieldGrounder
    remove_column :players, :fieldLiner
    remove_column :players, :fieldFlyball
    remove_column :players, :fieldPopup
    remove_column :players, :throwShort
    remove_column :players, :throwMedium
    remove_column :players, :throwLong
    remove_column :players, :intelligence
    remove_column :players, :endurance
    remove_column :players, :atbats
    remove_column :players, :runs
    remove_column :players, :hits
    remove_column :players, :doubles
    remove_column :players, :triples
    remove_column :players, :home_runs
    remove_column :players, :rbi
    remove_column :players, :walks
    remove_column :players, :strikeouts
    remove_column :players, :stolen_bases
    remove_column :players, :caught_stealing
    remove_column :players, :errors_committed
    remove_column :players, :assists
    remove_column :players, :putouts
    remove_column :players, :chances
    remove_column :players, :outs_recorded
    remove_column :players, :hits_allowed
    remove_column :players, :runs_allowed
    remove_column :players, :earned_runs_allowed
    remove_column :players, :walks_allowed
    remove_column :players, :strikeouts_recorded
    remove_column :players, :home_runs_allowed
    remove_column :players, :total_pitches
    remove_column :players, :strikes_thrown
    remove_column :players, :balls_thrown
    remove_column :players, :intentional_walks_allowed
    remove_column :players, :zone_1_pitches
    remove_column :players, :zone_2_pitches
    remove_column :players, :zone_3_pitches
    remove_column :players, :zone_4_pitches
    remove_column :players, :zone_5_pitches
    remove_column :players, :zone_6_pitches
    remove_column :players, :zone_7_pitches
    remove_column :players, :zone_8_pitches
    remove_column :players, :zone_9_pitches
    remove_column :players, :zone_10_pitches
    remove_column :players, :zone_11_pitches
    remove_column :players, :zone_12_pitches
    remove_column :players, :zone_13_pitches
    remove_column :players, :zone_14_pitches
    remove_column :players, :zone_15_pitches
    remove_column :players, :zone_16_pitches
    remove_column :players, :zone_17_pitches
    remove_column :players, :zone_18_pitches
    remove_column :players, :zone_19_pitches
    remove_column :players, :zone_20_pitches
    remove_column :players, :zone_21_pitches
    remove_column :players, :zone_22_pitches
    remove_column :players, :zone_23_pitches
    remove_column :players, :zone_24_pitches
    remove_column :players, :zone_25_pitches
    remove_column :players, :zone_26_pitches
    remove_column :players, :zone_27_pitches
    remove_column :players, :zone_28_pitches
    remove_column :players, :zone_29_pitches
    remove_column :players, :zone_30_pitches
    remove_column :players, :zone_31_pitches
    remove_column :players, :zone_32_pitches
    remove_column :players, :zone_33_pitches
    remove_column :players, :zone_34_pitches
    remove_column :players, :zone_35_pitches
    remove_column :players, :zone_36_pitches
    remove_column :players, :zone_37_pitches
    remove_column :players, :zone_38_pitches
    remove_column :players, :zone_39_pitches
    remove_column :players, :zone_40_pitches
    remove_column :players, :zone_41_pitches
    remove_column :players, :zone_42_pitches
    remove_column :players, :zone_43_pitches
    remove_column :players, :zone_44_pitches
    remove_column :players, :zone_45_pitches
    remove_column :players, :zone_46_pitches
    remove_column :players, :zone_47_pitches
    remove_column :players, :zone_48_pitches
    remove_column :players, :zone_49_pitches
    remove_column :players, :zone_50_pitches
    remove_column :players, :zone_51_pitches
    remove_column :players, :zone_52_pitches
    remove_column :players, :zone_53_pitches
    remove_column :players, :zone_54_pitches
    remove_column :players, :zone_55_pitches
    remove_column :players, :zone_56_pitches
    remove_column :players, :zone_57_pitches
    remove_column :players, :zone_58_pitches
    remove_column :players, :zone_59_pitches
    remove_column :players, :zone_60_pitches
    remove_column :players, :zone_61_pitches
    remove_column :players, :zone_62_pitches
    remove_column :players, :zone_63_pitches
    remove_column :players, :zone_64_pitches
    remove_column :players, :zone_65_pitches
    remove_column :players, :zone_66_pitches
    remove_column :players, :zone_67_pitches
    remove_column :players, :zone_68_pitches
    remove_column :players, :zone_69_pitches
    remove_column :players, :zone_70_pitches
    remove_column :players, :zone_71_pitches
    remove_column :players, :zone_72_pitches
    remove_column :players, :wins
    remove_column :players, :losses
    remove_column :players, :current_position
    remove_column :players, :lineup_position
    remove_column :players, :season_id
    remove_column :players, :static_id

  end
end
