class AddCurrentSeasonStatsAndAttributesBackToPlayers < ActiveRecord::Migration
  def change
    add_column :players, :power, :integer
    add_column :players, :contact, :integer
    add_column :players, :speed, :integer
    add_column :players, :patience, :integer
    add_column :players, :plate_vision, :integer
    add_column :players, :pull_amount, :integer
    add_column :players, :uppercut_amount, :integer
    add_column :players, :batting_average, :integer
    add_column :players, :movement, :integer
    add_column :players, :control, :integer
    add_column :players, :location, :integer
    add_column :players, :agility, :integer
    add_column :players, :reaction_time, :integer
    add_column :players, :arm_strength, :integer
    add_column :players, :field_grounder, :integer
    add_column :players, :field_liner, :integer
    add_column :players, :field_flyball, :integer
    add_column :players, :field_popup, :integer
    add_column :players, :throw_short, :integer
    add_column :players, :throw_medium, :integer
    add_column :players, :throw_long, :integer
    add_column :players, :intelligence, :integer
    add_column :players, :endurance, :integer
    add_column :players, :clutch, :integer
    add_column :players, :atbats, :integer
    add_column :players, :runs, :integer
    add_column :players, :hits, :integer
    add_column :players, :doubles, :integer
    add_column :players, :triples, :integer
    add_column :players, :home_runs, :integer
    add_column :players, :rbi, :integer
    add_column :players, :walks, :integer
    add_column :players, :intentional_walks, :integer
    add_column :players, :strikeouts, :integer
    add_column :players, :stolen_bases, :integer
    add_column :players, :caught_stealing, :integer
    add_column :players, :games, :integer
    add_column :players, :errors_committed, :integer
    add_column :players, :assists, :integer
    add_column :players, :putouts, :integer
    add_column :players, :chances, :integer
    add_column :players, :outs_recorded, :integer
    add_column :players, :hits_allowed, :integer
    add_column :players, :runs_allowed, :integer
    add_column :players, :earned_runs_allowed, :integer
    add_column :players, :walks_allowed, :integer
    add_column :players, :strikeouts_recorded, :integer
    add_column :players, :home_runs_allowed, :integer
    add_column :players, :total_pitches, :integer
    add_column :players, :strikes_thrown, :integer
    add_column :players, :balls_thrown, :integer
    add_column :players, :intentional_walks_allowed, :integer
    add_column :players, :wins, :integer
    add_column :players, :losses, :integer
    add_column :players, :saves, :integer
    add_column :players, :blown_saves, :integer
    add_column :players, :holds, :integer
    add_column :players, :zone_1_pitches, :integer
    add_column :players, :zone_2_pitches, :integer
    add_column :players, :zone_3_pitches, :integer
    add_column :players, :zone_4_pitches, :integer
    add_column :players, :zone_5_pitches, :integer
    add_column :players, :zone_6_pitches, :integer
    add_column :players, :zone_7_pitches, :integer
    add_column :players, :zone_8_pitches, :integer
    add_column :players, :zone_9_pitches, :integer
    add_column :players, :zone_10_pitches, :integer
    add_column :players, :zone_11_pitches, :integer
    add_column :players, :zone_12_pitches, :integer
    add_column :players, :zone_13_pitches, :integer
    add_column :players, :zone_14_pitches, :integer
    add_column :players, :zone_15_pitches, :integer
    add_column :players, :zone_16_pitches, :integer
    add_column :players, :zone_17_pitches, :integer
    add_column :players, :zone_18_pitches, :integer
    add_column :players, :zone_19_pitches, :integer
    add_column :players, :zone_20_pitches, :integer
    add_column :players, :zone_21_pitches, :integer
    add_column :players, :zone_22_pitches, :integer
    add_column :players, :zone_23_pitches, :integer
    add_column :players, :zone_24_pitches, :integer
    add_column :players, :zone_25_pitches, :integer
    add_column :players, :zone_26_pitches, :integer
    add_column :players, :zone_27_pitches, :integer
    add_column :players, :zone_28_pitches, :integer
    add_column :players, :zone_29_pitches, :integer
    add_column :players, :zone_30_pitches, :integer
    add_column :players, :zone_31_pitches, :integer
    add_column :players, :zone_32_pitches, :integer
    add_column :players, :zone_33_pitches, :integer
    add_column :players, :zone_34_pitches, :integer
    add_column :players, :zone_35_pitches, :integer
    add_column :players, :zone_36_pitches, :integer
    add_column :players, :zone_37_pitches, :integer
    add_column :players, :zone_38_pitches, :integer
    add_column :players, :zone_39_pitches, :integer
    add_column :players, :zone_40_pitches, :integer
    add_column :players, :zone_41_pitches, :integer
    add_column :players, :zone_42_pitches, :integer
    add_column :players, :zone_43_pitches, :integer
    add_column :players, :zone_44_pitches, :integer
    add_column :players, :zone_45_pitches, :integer
    add_column :players, :zone_46_pitches, :integer
    add_column :players, :zone_47_pitches, :integer
    add_column :players, :zone_48_pitches, :integer
    add_column :players, :zone_49_pitches, :integer
    add_column :players, :zone_50_pitches, :integer
    add_column :players, :zone_51_pitches, :integer
    add_column :players, :zone_52_pitches, :integer
    add_column :players, :zone_53_pitches, :integer
    add_column :players, :zone_54_pitches, :integer
    add_column :players, :zone_55_pitches, :integer
    add_column :players, :zone_56_pitches, :integer
    add_column :players, :zone_57_pitches, :integer
    add_column :players, :zone_58_pitches, :integer
    add_column :players, :zone_59_pitches, :integer
    add_column :players, :zone_60_pitches, :integer
    add_column :players, :zone_61_pitches, :integer
    add_column :players, :zone_62_pitches, :integer
    add_column :players, :zone_63_pitches, :integer
    add_column :players, :zone_64_pitches, :integer
    add_column :players, :zone_65_pitches, :integer
    add_column :players, :zone_66_pitches, :integer
    add_column :players, :zone_67_pitches, :integer
    add_column :players, :zone_68_pitches, :integer
    add_column :players, :zone_69_pitches, :integer
    add_column :players, :zone_70_pitches, :integer
    add_column :players, :zone_71_pitches, :integer
    add_column :players, :zone_72_pitches, :integer
  end
end
