module Bases
  EMPTY = 1
  RUNNER_ON_FIRST = 2
  RUNNER_ON_SECOND = 3
  RUNNER_ON_THIRD = 4
  RUNNERS_ON_FIRST_AND_SECOND = 5
  RUNNERS_ON_SECOND_AND_THIRD = 6
  RUNNERS_ON_FIRST_AND_THIRD = 7
  LOADED = 8
end
