module PitchLocationType
  WAY_OUTSIDE = "very far outside"
  WAY_HIGH = "very high"
  WAY_LOW = "very low"
  WAY_INSIDE = "very far inside"
  WAY_HIGH_AND_OUTSIDE = "very high and outside"
  WAY_HIGH_AND_INSIDE = "very high and inside"
  WAY_LOW_AND_OUTSIDE = "very low and outside"
  WAY_LOW_AND_INSIDE = "very low and inside"

  JUST_OUTSIDE = "just off the outside corner"
  JUST_HIGH = "just above the letters"
  JUST_LOW = "just below the knees"
  JUST_INSIDE = "just off the inside corner"
  JUST_HIGH_AND_OUTSIDE = "just off the high outside corner"
  JUST_HIGH_AND_INSIDE = "just off the high inside corner"
  JUST_LOW_AND_INSIDE = "just off the low inside corner"
  JUST_LOW_AND_OUTSIDE = "just off the low outside corner"

  AT_THE_LETTERS = "at the letters"
  AT_THE_KNEES = "at the knees"
  ON_THE_INSIDE_CORNER = "on the inside corner"
  ON_THE_OUTSIDE_CORNER = "on the outside corner"
  AT_THE_LETTERS_ON_THE_INSIDE_CORNER = "on the high inside corner"
  AT_THE_LETTERS_ON_THE_OUTSIDE_CORNER = "on the low outside corner"
  AT_THE_KNEES_ON_THE_INSIDE_CORNER = "on the low inside corner"
  AT_THE_KNEES_ON_THE_OUTSIDE_CORNER = "on the low outside corner"

  ON_THE_UPPER_HALF = "on the upper half"
  ON_THE_LOWER_HALF = "on the lower half"
  ON_THE_INNER_HALF = "on the inner half"
  ON_THE_OUTER_HALF = "on the outer half"
  ON_THE_UPPER_INNER_HALF = "on the upper inner half"
  ON_THE_UPPER_OUTER_HALF = "on the upper outer half"
  ON_THE_LOWER_INNER_HALF = "on the lower inner half"
  ON_THE_LOWER_OUTER_HALF = "on the lower outer half"

  DOWN_THE_MIDDLE = "down the middle"
end
