module PitchLocationType
  WAY_OUTSIDE = 1
  WAY_HIGH = 2
  WAY_LOW = 3
  WAY_INSIDE = 4
  WAY_HIGH_AND_OUTSIDE = 5
  WAY_HIGH_AND_INSIDE = 6
  WAY_LOW_AND_OUTSIDE = 7
  WAY_LOW_AND_INSIDE = 8

  JUST_OUTSIDE = 9
  JUST_HIGH = 10
  JUST_LOW = 11
  JUST_INSIDE = 12
  JUST_HIGH_AND_OUTSIDE = 13
  JUST_HIGH_AND_INSIDE = 14
  JUST_LOW_AND_INSIDE = 15
  JUST_LOW_AND_OUTSIDE = 16

  AT_THE_LETTERS = 17
  AT_THE_KNEES = 18
  ON_THE_INSIDE_CORNER = 19
  ON_THE_OUTSIDE_CORNER = 20
  AT_THE_LETTERS_ON_THE_INSIDE_CORNER = 21
  AT_THE_LETTERS_ON_THE_OUTSIDE_CORNER = 22
  AT_THE_KNEES_ON_THE_INSIDE_CORNER = 23
  AT_THE_KNEES_ON_THE_OUTSIDE_CORNER = 24

  ON_THE_UPPER_HALF = 25
  ON_THE_LOWER_HALF = 26
  ON_THE_INNER_HALF = 27
  ON_THE_OUTER_HALF = 28
  ON_THE_UPPER_INNER_HALF = 29
  ON_THE_UPPER_OUTER_HALF = 30
  ON_THE_LOWER_INNER_HALF = 31
  ON_THE_LOWER_OUTER_HALF = 32

  DOWN_THE_MIDDLE = 33
end
